### ISSUE TITLE
请问下，我怎么运行tomcat报错..

### ISSUE THREAD

**Issue by Ryoui** [abel533/Mybatis-Spring#29]
clone下来，然后导入eclipse，jdk默认1.5改成1.8，并修改config.properties后，运行tomcat报错，
tomcat7.0报：
` org.apache.catalina.loader.WebappClassLoaderBase findResourceInternal
严重: Resource read error: Could not load com/alibaba/druid/sql/ast/SQLExpr.class.
java.util.zip.ZipException: invalid LOC header (bad signature)`
tomcat9.0报：
`严重: A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.JarResourceSet@194fad1]`，
而整合了分页插件的项目，同样的方式，就不报错，
为什么呢？

**Comment by abel533** [comment]
一般是jar包拷的过程出错导致不完整。
