### ISSUE TITLE
在我本地运行的时候发现当前版本的两个问题

### ISSUE THREAD

**Issue by HanQingMoMo** [abel533/Mybatis-Spring#36]
当前git项目版本号：fe06ab26fde7430fc112f4ce555b2362841973c9
<1> 版本问题：将mybatis.spring.version的版本更改为1.3.0
 <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        
        <jdk.version>1.8</jdk.version>
        
        <mybatis.version>3.4.1</mybatis.version>
        <mapper.version>4.0.0</mapper.version>
        <pagehelper.version>5.0.0</pagehelper.version>
        <mysql.version>5.1.29</mysql.version>
        <spring.version>4.1.2.RELEASE</spring.version>
        <mybatis.spring.version>1.3.0</mybatis.spring.version>
    </properties>
否则会报错，参考https://blog.csdn.net/Zhiyuan_Ma/article/details/69396275
<2> 测试中的问题
 将Mybatis-Spring/src/test/java/com/isea533/mybatis/test/BasicTest.java设置为抽象类
参考 https://stackoverflow.com/questions/672466/junit-how-to-avoid-no-runnable-methods-in-test-utils-classes gmoore的回答。

本人小白，上面的言论如有问题。。。。😁概不负责

**Comment by abel533** [comment]
可能存在这个问题。
