### ISSUE TITLE
jar有问题

### ISSUE THREAD

**Issue by kings1990** [abel533/Mybatis-Spring#4]
感觉这个jar有问题
<dependency>
            <groupId>tk.mybatis</groupId>
            <artifactId>mapper</artifactId>
            <version>3.1.3-SNAPSHOT</version>
        </dependency>
我调用了Mapper类里面的selectByPrimaryKey方法，它在查询的时候不只是带上了id，还且还吧其他字段也带上了，导致查询不到结果

**Comment by abel533** [comment]
你的实体类肯定没有`@Id`,这种情况下，所有子段作为联合主键。。通用Mapper文档有说明。

**Comment by kings1990** [comment]
恩  大神我已经解决了 研究了下你写的东西 感觉好给力 能帮省去好多无脑的工作  支持大神哦！！！
