### ISSUE TITLE
这个框架@ResponseBody 为何不能返回json

### ISSUE THREAD

**Issue by liliexuan** [abel533/Mybatis-Spring#7]
这个基础框架返回json怎么有问题？他总是自动返回请求名称+.jsp的页面，然后报404错误！
@abel533

**Comment by abel533** [comment]
你返回的什么对象？

**Comment by liliexuan** [comment]
map对象。是我用法错误了，我以为只要是用了@ResponseBody它就会返回json，后来在咱们群里问了才知道是用通过ajax 设置返回数据类型是json它才会返回json.
